all: clean doit

clean:
	rm -r -f ../archive.html ../2012/ ../rss.xml ../favicon.ico ../sitemap.xml.gz
	rm -r -f ../assets/ ../categories/ ../galleries/ ../index.html ../posts/ ../stories/

doit:
	doit

